@startuml
left to right direction
skinparam packageStyle rectangle

actor Consultor
actor Gerente
actor "Chefe de oficina" as Chefe
actor "Setor de Peças" as Pecas

package "CarManager" {
  package "Cadastro\n(C#)" as cadastro {
    [Cadastro de clientes e veículos]
    [Abertura de ordem de serviço]
  }
  package "Controle\n(C#)" as controle {
    [Controle de ordem de serviços]
  }
  package "Peças\n(C#)" as pecas_c {
    [Recebe pedido das peças]
  }
  database "Banco de Dados\n(MySQL)" as db
}

Consultor --> cadastro : "Cadastra clientes, veículos\ne serviços"
cadastro --> Chefe : "Envia informações do veículo"
cadastro --> pecas_c : "Ao cadastrar veículo\nenvia pedido de peças"
pecas_c --> Pecas : "Pedido de peças"
Chefe --> controle : "Visualização e\napontamento de produtivo"
controle --> Gerente : "Visualização geral"
cadastro --> db : "Armazena dados"
controle --> db : "Armazena dados"
pecas_c --> db : "Armazena dados"

@enduml