name: Render PlantUML Diagrams

on:
  push:
    paths:
      - '**/*.puml'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: plantuml-render
  cancel-in-progress: true

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositório
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Instalar dependências
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz default-jre

      - name: Baixar PlantUML
        run: |
          curl -L -o plantuml.jar https://github.com/plantuml/plantuml/releases/latest/download/plantuml.jar

      - name: Gerar diagramas (PNG + SVG)
        run: |
          mkdir -p diagrams
          find . -name "*.puml" -print0 | while IFS= read -r -d '' file; do
            java -jar plantuml.jar -tpng "$file" -o diagrams
            java -jar plantuml.jar -tsvg "$file" -o diagrams
          done

      - name: Commitar imagens geradas
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add diagrams || true
          git commit -m "Atualiza diagramas renderizados" || echo "Nada para commitar"
          git push origin HEAD:$(git rev-parse --abbrev-ref HEAD) || echo "Push falhou (verificar permissões)"
